# cleansh-workspace/Cargo.toml
[workspace]
members = [
    "cleansh-core",
    "cleansh",
    "cleansh-entropy",
]
resolver = "2" 

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dist]
inherits = "release"
lto = "thin"
